WIP: Gh pages imu data csv fix
annotell/annotell-python pull request #122
Opened 2022-01-31 14:50 UTC by alydh-annotell

2022-02-02 13:08 UTC, Ragge-dev commented on docs-src/docs/input-api/resources/pointclouds.md
> +We currently only support the following exact header and separation character (where `intensity` is uint8, `ts_gps` is long and `x`, `y`, `z` are all float32):
I think long is not that specific, it can be different things for different languages. Since an integer is what is used by clients atm I think we will need it to be a at least a uint64. (could be signed as well, but no need for an epoch time) In the future I think this would be better as a float as well

2022-02-02 13:31 UTC, Ragge-dev commented on docs-src/docs/input-api/inputs/lidars_with_imu_data.md
> +```
I don't know if we should have this example here, to me this is mainly useful simply as a utility tool for us (similar to the code we have to create a unity calibration). The first example I think should be sufficient

2022-02-02 13:36 UTC, Ragge-dev requested changes
The new chapter is not visible in the documentation, in order to add it there you will need to add it under a suitable place in `docs-src/sidebars.js`. I'm thinking this chapter could be under the "Inputs" tab, I feel like we probably want to break out a lot under "Overview" in due time and give e.g. Calibrations a separate tab.

When in docs-src you can run: `npm run docusaurus start` in order to view how the documentation will look

2022-02-24 10:00 UTC, alydh-annotell commented
LGTM

2022-02-24 10:01 UTC, merged