WIP: Int 1103 add pre annotations support in input api client
annotell/annotell-python pull request #154
Opened 2022-05-23 07:28 UTC by alydh-annotell

2022-05-23 14:03 UTC, petern-annotell approved these changes

2022-05-23 14:32 UTC, alydh-annotell commented on annotell-input-api/tests/lidars_and_cameras_seq_with_pre_annotations_test.py
> +    def test_validate_lidars_cameras_seq_with_imu_and_shutter_times_example(self, client: IAC.InputApiClient):
No i'll update them

2022-05-31 15:20 UTC, alydh-annotell commented
Ran this towards the test setup in staging and it creates inputs with preannotations

2022-06-01 15:15 UTC, olinoskar requested changes
A few comments. We also need to add `annotell-openlabel` in setup.py now

2022-06-01 15:15 UTC, olinoskar commented on annotell-input-api/annotell/input_api/model/input/preannotations/validated_pre_annotations.py
> +from typing import Optional
remove file

2022-06-01 15:15 UTC, olinoskar commented on annotell-input-api/annotell/input_api/model/input/preannotations/__init__.py
> +from .validated_pre_annotations import *
remove file

2022-06-01 15:15 UTC, olinoskar commented on annotell-input-api/examples/lidars_and_cameras_seq_with_pre_annotations.py
> +    time.sleep(10)
add a print (or log) here to make it clear that we are sleeping and that nothing is wrong

2022-06-07 13:15 UTC, olinoskar approved these changes

2022-06-09 07:38 UTC, merged