Convert dataclasses to pydantic
annotell/annotell-python pull request #195
Opened 2022-10-13 07:24 UTC by petern-annotell

All remaining `@dataclass`-es have been ported over to pydantic models.

Quite a lot of changes that fall into some patterns:
- Replacing the dataclass annotations by extending from `BaseSerializer`
- Removing custom `to_dict` and `from_json` impls and adding field aliases instead
- Set default values on fields that previously could be empty, so that they don't have to be specified everywhere
- Juggled a lot of imports with @olinoskar 's help; this prevented a circular dependency but means some classes that could be imported from any input model sub-package no longer can.

Clients will need to update their code. I will create a separate PR for updating the docs with a migration guide.

2022-10-13 10:58 UTC, kallus requested changes
Very nice to see a negative change of LOC count! :)

2022-10-13 10:58 UTC, kallus commented on kognic-io/kognic/io/model/projects/project_batch.py
> +    # TODO for created/updated does ts_to_dt need to be given as a validator (or something) with pydantic,
```suggestion
```
I think we should avoid checking in TODO lines. I suggest adding this to jira instead if it in not convenient to solve it now.

2022-10-13 11:57 UTC, petern-annotell commented on kognic-io/kognic/io/model/projects/project_batch.py
> +    # TODO for created/updated does ts_to_dt need to be given as a validator (or something) with pydantic,
Yep good catch :+1: will nuke it

2022-10-14 11:51 UTC, kallus approved these changes

2022-10-14 12:19 UTC, kallus approved these changes
LGTM

2022-10-14 12:22 UTC, merged