Add support for passing bytes
annotell/annotell-python pull request #209
Opened 2022-10-31 12:26 UTC by petern-annotell

Adds two new ways to pass binary data for images and pointclouds:

```py
# immediately from a pre-determined blob of data:
data: bytes = ... 
image = Image(..., data=FileData(data=data, format=FileData.Format.JPG))

# incrementally, from a callback:
def my_callback(name: str) -> bytes:
   ...

Image(..., data=FileData(callback=my_callback, format=FileData.Format.JPG))
```

2022-10-31 16:46 UTC, olinoskar requested changes
Great job! I really like what you did with `FileData` and `UploadSpec`. I have a few comments that I think that you can have a look at. No major things though. 

Apart from the comments I also thought that about the file extensions on FileData. Currently if you pass 

```python
Image(filename="foo.bar", sensor_name="cam1", data=FileData(data=data, format=FileData.Format.JPG))
```

you get `foo.bar.jpg`. Wouldn't it be better to validate that these extensions are the same instead? Otherwise you would get `foo.png.jpg` if you pass

```python
Image(filename="foo.png", sensor_name="cam1", data=FileData(data=data, format=FileData.Format.JPG))
```

which doesn't really make sense. On the other hand, we can say that this specific use case is not allowed. Not sure what I think here...

2022-10-31 16:46 UTC, olinoskar commented on kognic-base-clients/kognic/base_clients/cloud_storage/upload_handler.py
> +    def _upload_from_local_file(self, upload_spec: UploadSpec, folder: Optional[Path]):
I wonder if the `folder` parameter can be removed here and in the methods using this one. I don't see it being used anywhere now

2022-10-31 16:46 UTC, olinoskar commented on kognic-base-clients/kognic/base_clients/cloud_storage/upload_handler.py
> +        self._upload(upload_spec, upload_spec.data)
The types won't be correct here. You will get `bytes` from `upload_spec.data` but the `_upload` method requires an `IOBase`. Perhaps you could convert it to a `BytesIO`?

2022-10-31 16:46 UTC, olinoskar commented on kognic-base-clients/kognic/base_clients/cloud_storage/upload_handler.py
> +            self._upload(upload_spec, data)
Same comment as above regarding the types

2022-10-31 16:46 UTC, olinoskar commented on kognic-io/kognic/io/resources/input/file_data.py
> +            raise ValueError(f"Only one of data or callback may be set on FileData")
I think it would be good to check the type of `data` here

2022-10-31 16:46 UTC, olinoskar commented on kognic-io/kognic/io/resources/input/file_data.py
> +    data: Optional[bytes]
Can we use a better name than `data`, which can mean anything. I don't have any great suggestions though. Maybe `content`, but that's kind of the same. No need to change this if you can't come up with anything better

2022-10-31 16:46 UTC, olinoskar commented on kognic-io/kognic/io/resources/input/file_data.py
> +    Describes a source of file data to upload to the input API at a later point.
I have tried to avoid using `input API` in the documentation. I think that you can simply remove that here.

In addition, we should probably add a docstring here with a description about the different parameters. This is especially important on this model since users will use this directly.

2022-10-31 16:46 UTC, olinoskar commented on kognic-io/kognic/io/resources/input/lidars.py
> +            raise ValueError(f"Cannot create a {type(lidars)} via this endpoint")
Please remove this. This will get the a "not supported" issue from the input api if they try to use this. We have also removed all references to this in the documentation. The reason for not removing it, is if we want to revive it at some point. Then they don't have to use another version of the client. If we want to remove support in the client directly, I think that we should remove all this instead

2022-10-31 16:46 UTC, olinoskar commented on kognic-io/kognic/io/resources/input/lidars_sequence.py
> +            raise ValueError(f"Cannot create a {type(lidars_sequence)} via this endpoint")
Remove. See reason above

2022-10-31 16:46 UTC, olinoskar commented on kognic-io/tests/create_input_from_bytes_test.py
> +class TestCreateInputFromBytes:
Perhaps you can rename this to `TestCreateSceneFromMemory` or similar since it covers both bytes and callback

2022-10-31 16:46 UTC, olinoskar commented on kognic-io/tests/create_input_from_bytes_test.py
> +class TestCreateInputFromBytes:
Or maybe there should be two separate tests. One for bytes and one for callbacks?

2022-10-31 16:55 UTC, olinoskar commented
Another thing I though of now is that we could make the callback accept any key-word arguments

```python
class UploadSpec:
    data: Optional[bytes]
    callback: CallbackFunction
    callback_kwargs: dict # passed to callback
    ...

def _upload_from_callback(self, upload_spec: UploadSpec):
    # also with the try-block
    data = upload_spec.callback(upload_spec, filename, **upload_spec.callback_kwargs)
    self._upload(upload_spec, data)
```

Do what you want with this though. It could also be a nice future improvement

2022-11-01 13:45 UTC, petern-annotell commented on kognic-base-clients/kognic/base_clients/cloud_storage/upload_handler.py
> +    def _upload_from_local_file(self, upload_spec: UploadSpec, folder: Optional[Path]):
Will do as a separate PR just to keep this clean(ish)

2022-11-01 13:46 UTC, petern-annotell commented on kognic-base-clients/kognic/base_clients/cloud_storage/upload_handler.py
> +        self._upload(upload_spec, upload_spec.data)
Good catch, probably knew what I intended here and just didn't write it correctly! Will revisit.

2022-11-01 13:47 UTC, petern-annotell commented on kognic-io/kognic/io/resources/input/file_data.py
> +    data: Optional[bytes]
I'm happy with data because I can't really come up with anything, and it _is_ the filedata's data

2022-11-01 13:50 UTC, petern-annotell commented on kognic-io/kognic/io/resources/input/lidars.py
> +            raise ValueError(f"Cannot create a {type(lidars)} via this endpoint")
This is just a check that you're trying to create a lidars via the lidars endpoint, not any other kind of input -- I put it here so all the `.create` methods are consistent (then as you can say, we can revive it a bit more straight-forwardly). Is that not great?

2022-11-01 14:01 UTC, petern-annotell commented
> Another thing I though of now is that we could make the callback accept any key-word arguments

Hmmmm! I do like the idea of allowing arbitrary extra args to be passed to the callback. But, in that case, I _think_ it's possible to bake the args into the callback to achieve this... kind of how in scala if you have to do `foo(1)(2)` you could pass `foo(1)` as a callback? So the caller can create a closure over their kwargs before they give us the "rest" of the function.

```python
def my_callback(name1, named2, **kwargs):
    def inner(filename):
        # do something with filename, arg1, arg2 and kwargs.
    return inner

FileData(..., callback=my_callback)
```

2022-11-01 14:23 UTC, olinoskar commented on kognic-io/kognic/io/resources/input/lidars.py
> +            raise ValueError(f"Cannot create a {type(lidars)} via this endpoint")
You're right. Sorry for not reading carefully

2022-11-01 14:25 UTC, olinoskar commented
> > Another thing I though of now is that we could make the callback accept any key-word arguments
> 
> Hmmmm! I do like the idea of allowing arbitrary extra args to be passed to the callback. But, in that case, I _think_ it's possible to bake the args into the callback to achieve this... kind of how in scala if you have to do `foo(1)(2)` you could pass `foo(1)` as a callback? So the caller can create a closure over their kwargs before they give us the "rest" of the function.
> 
> ```python
> def my_callback(name1, named2, **kwargs):
>     def inner(filename):
>         # do something with filename, arg1, arg2 and kwargs.
>     return inner
> 
> FileData(..., callback=my_callback("some", "args", ... )
> ```

Good idea. We could add an example in the docs about this. I am sure that someone will ask about it.

2022-11-02 12:50 UTC, petern-annotell commented
Done! See https://github.com/annotell/public-docs/pull/1

2022-11-02 14:51 UTC, petern-annotell commented on kognic-io/kognic/io/resources/input/file_data.py
> +            raise ValueError(f"Only one of data or callback may be set on FileData")
Turns out to be a pain since the type is now a union and cannot be used in `isinstance` in this context apparently!

2022-11-02 15:37 UTC, petern-annotell commented on kognic-base-clients/kognic/base_clients/cloud_storage/upload_handler.py
> +    def _upload_from_local_file(self, upload_spec: UploadSpec, folder: Optional[Path]):
#211

2022-11-04 10:25 UTC, olinoskar approved these changes
Nice!

2022-11-07 10:11 UTC, merged