Sp 497 function to create scenes and inputs approach 3
annotell/annotell-python pull request #234
Opened 2023-03-31 09:14 UTC by luisf-annotell

Reimplements the scene job waiting process + some cleanup.

2023-03-31 09:26 UTC, olinoskar commented on kognic-io/kognic/io/tools/scene_input.py
> +        scenes = client.input.get_inputs_by_uuids(remaining_scenes_uuids)
I think that we need to limit the number of uuids we send here since this route tends to fail with many uuids. I think that a around a 100 should be a good number

2023-03-31 09:29 UTC, olinoskar commented on kognic-io/kognic/io/tools/scene_input.py
> +        remaining_scenes_uuids = []
Why not use a set instead? Then you won't have to convert it to a set on line 88

2023-03-31 09:31 UTC, olinoskar requested changes
I don't think we can fetch all scenes at once so that needs to be changed. Otherwise it looks good

2023-03-31 09:31 UTC, luisf-annotell commented on kognic-io/kognic/io/tools/scene_input.py
> +        remaining_scenes_uuids = []
Oops

2023-03-31 09:37 UTC, AndersNordmark commented on kognic-io/kognic/io/tools/scene_input.py
> +                remaining_scenes_uuids.append(scene.uuid)
Won't the completed scenes also be appended here? Which means that they will be polled and returned again? Or am I missing something?

2023-03-31 14:14 UTC, olinoskar commented on kognic-io/kognic/io/tools/scene_input.py
> +                completed.append(scene_uuid)
En mindre detalj kanske men du kan egentligen bara köra `remaining_scenes_uuids.remove(scene_uuid)` här så kan du droppa `completed` helt och hållet

2023-03-31 14:21 UTC, luisf-annotell commented on kognic-io/kognic/io/tools/scene_input.py
> +                completed.append(scene_uuid)
Hmm hade nåt sånt från början tror jag, minns inte varför jag ändrade...

2023-03-31 14:22 UTC, olinoskar commented on kognic-io/kognic/io/tools/scene_input.py
> +    count = 0
This can be shortened quite a lot with a one liner. Try this
```python
return [origin_list[i:i+chunk_size] for i in range(0, len(origin_list), chunk_size)]
```
The function would then accept a list intead and return a list of lists instead

2023-03-31 14:25 UTC, olinoskar requested changes
I think that the logic is much better now and we shouldn't run into issues with the input-api. There are still some minor changes that can be done though to make the code a bit prettier

2023-03-31 14:49 UTC, luisf-annotell commented on kognic-io/kognic/io/tools/scene_input.py
> +    count = 0
Huh, I thought I'd get an error if I tried an index larger than the list length. But even so, I'd rather keep this approach that works with sets, saves me having to convert back and forth in the main code.

2023-04-03 09:13 UTC, olinoskar commented on kognic-io/kognic/io/tools/scene_input.py
> +    count = 0
You don't have to convert back and forth in the main method. Just in the call to this method. And if you don't want to do that you can simply add an extra line to this function and convert from set to list

2023-04-11 07:57 UTC, olinoskar commented on kognic-io/kognic/io/tools/scene_input.py
> +    while time.time() - start_time < wait_timeout:
A very minor thing that you can address if you want to
```suggestion
    while time.time() - start_time < wait_timeout and len(remaining_scenes_uuids) > 0:
```

2023-04-11 08:02 UTC, olinoskar commented on kognic-io/kognic/io/tools/scene_input.py
> +NORMAL_CHUNK_SIZE = 1000
I don't think that 1000 is ever going to work actually. Maybe 100 is more reasonable
```suggestion
NORMAL_CHUNK_SIZE = 100
```

2023-04-11 08:03 UTC, olinoskar commented on kognic-io/tests/tools_scene_input_test.py
> +class TestLidarsAndCamerasSeqWithPreAnnotations:
Rename class

2023-04-11 08:05 UTC, olinoskar approved these changes
There are still a few minor things that I would like you to change but feel free to merge when that's done. Great job!

2023-04-11 08:10 UTC, luisf-annotell commented on kognic-io/kognic/io/tools/scene_input.py
> +NORMAL_CHUNK_SIZE = 1000
Oops, used it for testing, forgot to change back.

2023-04-11 08:28 UTC, merged