add download annotation by annotation type
annotell/annotell-python pull request #91
Opened 2021-09-13 09:28 UTC by fredrikjacobson

Add support for fetching annotations via project/batch/annotation-type. 

`get_annotations` will return a `Generator[dict]`, meaning that we will yield the annotations and not fetch them in one request. I expect this to be **slow**, but it gives us the flexibility to change the implementation of internal storage.

This way you can either iterate or call `list` on the generator. (Which we need to add a notice on in the docs). 

Further, I expect `get_annotation` to be the primary way of downloading annotations when using callbacks.

2021-09-13 09:50 UTC, olinoskar requested changes

2021-09-13 09:50 UTC, olinoskar commented on annotell-input-api/annotell/input_api/resources/annotation/annotation.py
> +        if annotation_type:
Shouldn't we always include `annotation_type` in the url?

2021-09-13 10:27 UTC, fredrikjacobson commented on annotell-input-api/annotell/input_api/resources/annotation/annotation.py
> +        if annotation_type:
Yes!

2021-09-13 11:23 UTC, olinoskar approved these changes

2021-09-14 12:40 UTC, cotramarko commented on annotell-input-api/annotell/input_api/model/annotation/client_annotation.py
> +    annotation: Optional[Dict] = None
Should this be `Optional`?

2021-09-14 14:26 UTC, cotramarko requested changes

2021-09-15 14:08 UTC, fredrikjacobson commented on annotell-input-api/annotell/input_api/model/annotation/client_annotation.py
> +    annotation: Optional[Dict] = None
I had ideas about exposing the list entity itself, but might actually change to only exposing the resolved one, which will remove this optionality, and expose `Annotation`  which will be a class

2021-09-20 06:05 UTC, merged